language: java

jdk:
  - oraclejdk8

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

branches:
  only:
    - master

before_install:
 - chmod +x gradlew

script:
  - ./gradlew clean
  - ./gradlew build

before_deploy:
  - git config --local user.name "Whazaaaaa"
  - git config --local user.email "mrwhazaaaaa@hotmail.com"
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"

deploy:
  provider: releases
  api_key: $token
  file: build/libs/*
  skip_cleanup: true